name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2.1.3
      with:
        path: |
          vendor/bundle
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "gem install bundler:1.15.4 && bundle --deployment && chmod 777 /srv/jekyll && jekyll build --future"
